### ISSUE TITLE
SSG-EG documentation

### ISSUE THREAD

**Issue by 2xAA** [rhargreaves/mega-drive-midi-interface#42]
How do the 16 CC values on 90, 91, 92 and 93 map to the YM2612 SSG-EG?

It doesn't seem to match up with genMDM, though genMDM was confusing in its approach to the SSG-EG mapping (https://chipmusic.org/forums/post/264746/#p264746).

It would be great to have a table of values next to the SSG-EG waveforms, something like this: https://plutiedev.com/ym2612-registers#reg-90

**Comment by rhargreaves** [comment]
When I originally mapped SSG-EG I didn't really pay too much attention into what the bits actually meant. In fact, I just attempted to replicate what GenMDM had documented; that it was a 4-bit value with an effective range of 16. As such, the values should map accordingly:

0 - 63 = OFF (enable bit set to 0)
64 - 71 = Pattern 1
72 - 79 = Pattern 2
80 - 87 = Pattern 3
88 - 95 = Pattern 4
96 - 103 = Pattern 5
104 - 111 = Pattern 6
112 - 119 = Pattern 7
120 - 127 = Pattern 8

From that blog post though, it seems that GenMDM applies the range across MIDI CC value 0 to 63, and then repeats the same mappings from 64 to 127. In addition, the Max 4 Live range of 0-31 looks like a bug. It should be 0-63 considering the findings of the blog post.

Neither approach is particularly intuitive, considering a large portion of the range is "OFF". As for the GenMDM range, maybe the 0-64 range and subsequent repetition is a bug? I can't see a reason why you'd want such repetition. 

Arguably a better alternative would be to represent OFF as a "null pattern" and have in effect the "9 patterns" spread across the CC range. However, 128 doesn't divide cleanly into 9. So again, not exactly ideal. 

Considering the confusion, I will document the above so that it's made clear what MDMI does with the values. Not sure I want to change the behaviour to match GenMDM considering it's a bit... odd 🙃

**Comment by rhargreaves** [comment]
[Documentation updated](https://github.com/rhargreaves/mega-drive-midi-interface/wiki/MIDI-CCs-&-Events#ssg-eg)

**Comment by 2xAA** [comment]
That makes complete sense to keep it the same, thanks!

I'm working on a lot of MDMI specific updates to [genMDM Editor](https://github.com/2xAA/genmdm-editor) at the moment, which includes a specific MDMI mode.

This will toggle features supported by genMDM and MDMI, including the different mapping for SSGEG.
