### ISSUE TITLE
Algorithms 4 and 5 might be swapped?

### ISSUE THREAD

**Issue by 2xAA** [rhargreaves/mega-drive-midi-interface#45]
I'm not quite sure how or why, but I think algorithms 4 and 5 are swapped somehow.
This Deflemask 2OP Square Lead sound (from [Delfamask legacy](https://www.deflemask.com/get_legacy/)) uses algorithm 4 but comparing MDMI's output it sounds like it's using algorithm 5.

And comparing MDMI with GenMDM, GenMDM seems to handle this correctly.

I've included a .tfi and the .dmp file in this ZIP.
[2OP Square Lead.zip](https://github.com/user-attachments/files/17270095/2OP.Square.Lead.zip)

I'm using v.1.23.

**Comment by 2xAA** [comment]
Update - they're not swapped but also 4 seems incorrect.

**Comment by rhargreaves** [comment]
When I set the FM parameters to what is in DefleMask based on that preset - I get a sound which sounds the same:

<img width="752" alt="image" src="https://github.com/user-attachments/assets/a12a59eb-853f-4e86-8cc0-4dff4adad13b">

<img width="482" alt="image" src="https://github.com/user-attachments/assets/6e435dc7-eda0-4307-ada5-cd87e7628a08">

Are you setting the parameters via MIDI or embedding them as a preset in the C code?

**Comment by 2xAA** [comment]
I'm sending MIDI CCs from genMDM Editor.

I believe the issue is actually with Deflemask.
For some reason it saves operators 2 and 3 swapped in the .dmp patch format.

I had asked why here and forgot:
https://www.deflemask.com/forum/general/why-are-fm-operators-2-and-3-swapped/

Odd that GenMDM sounds exactly like Deflemask though. I'll do some more testing and see what I can find.

Maybe there's another compatibility SysEx that needs writing 🙃

Can close this for now.

**Comment by 2xAA** [comment]
Turns out GenMDM does swap operators 2 and 3 from an audio test.
MDMI's got it right, but as I was loading from a .dmp file which also swaps OP2 and OP3 it sounded incorrect.

This is something I'll handle in the editor.

**Comment by rhargreaves** [comment]
A lot of the confusion stems from incorrect SEGA documentation. I wrote some info about this on the [algorithm shapes](https://github.com/rhargreaves/mega-drive-midi-interface/wiki/FM-Algorithms#algorithm-shape-confusion) wiki page. Esssentially, whilst the SEGA doc got the shapes of the algorithms correct, they got the registers for OP2 and OP3 muddled up (saying it was OP1, OP2, OP3 and OP4). The register layout is actually OP1, OP3, OP2, OP4. Because of this unusual ordering of registers, I suppose some sound drivers simply mimic the register layout in their instrument definition patches. However, this then results in confusion as it conflicts with the logical shapes of the algorithms.

Since the register layout is, in my view, a purely internal implementation detail, I handle the swapping of OP2 and OP3 at a very low level, so everything exposed within MDMI, including UI, MIDI CCs, and even the instrument definition code blocks, respect the logical algorithm operator ordering as shown by the shapes above.
